### PR TITLE
add date change on arrow click

### PR DESCRIPTION
**Pull request by Sh1pley**
@kheppenstall @case-eee 

adds function to change date to tomorrow with forward arrow, yesterday with back arrow and reset to current day by clicking middle.

The change back to current day is a bit tacky and I will work on getting the arrows to do plus day/minus day from current state.. but thats a lesson to be learned! 

Sooo small win.

### CODE REVIEW

**Comment by kheppenstall** [comment]
@Sh1pley Right now the date does not toggle more than once since we are not saving state. I tried to make toggle both ways indefinitely and this is what I came up with. 

```javascript
var time = moment();

$("document").ready(function() {
  calculateCalorieSums();
  populateTotalsTable();
  addColorToRemainingCalories();
  displayDay();
  dayButtons();
})

function dayButtons() {
  $('button.forward').on('click', function() {
    time = time.add(1, 'day');
    displayDay();
  });

  $('button.back').on('click', function() {
    time = time.add(-1, 'day');
    displayDay();
  });
}

function displayDay() {
  $('.current-day section').html(time.format("dddd, MMMM Do YYYY"));
}

```

**Comment by kheppenstall** [comment]
This way `time` is saved as a variable and just gets changed and redisplayed each time one of the arrow buttons are clicked. Thoughts?

**Comment by Sh1pley** [comment]
I like this. Had a git brain fart, closing the other PR to more accurately track our progress with this item.

**Comment by Sh1pley** [comment]
went through a corrected the merge issues, @kheppenstall please double check that I didn't get rid of anything we need.

**Comment by kheppenstall** [comment]
@Sh1pley looks good!

**Comment by case-eee** [comment]
awesome job y'all @Sh1pley @kheppenstall 👍

**Pull request merged**
